name: Sign Container Image with Notation Trusted Signing Plugin

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:

env:
  REGISTRY: notationreg.azurecr.io
  IMAGE_NAME: hello-world
  IMAGE_TAG: ${{ github.ref_name }}  # Use the tag name as the image tag

jobs:
  sign-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC token
      contents: read    # Required to read repository contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure CLI Login with Federated Credentials
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.REGISTRY }}

    - name: Install Notation
      uses: notaryproject/notation-action/setup@v1
      with:
        version: "1.3.1"

    - name: Build and Push Docker Image
      run: |
        # Build the image
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        
        # Push the image
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Sign Image with Notation
      uses: notaryproject/notation-action/sign@v1
      with:
        plugin_name: azure-trustedsigning
        plugin_url: https://github.com/JeyJeyGao/notation-plugin-test/raw/refs/heads/main/plugins/notation-azure-trustedsigning_0.2.0-alpha.1_linux_amd64.tar.gz
        plugin_checksum: ce52f63659f41115cebced1e479a1c6c920c388d7699e4bdd5426657e339f59e
        key_id: ts
        target_artifact_reference: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        signature_format: cose
        plugin_config: |-
          certProfile=junjieNotationTest
          accountName=junjietts
          baseUrl="https://eus.codesigning.azure.net/"
        
    # - name: Verify Signature
    #   run: |
    #     # Install notation if not already available in PATH
    #     notation version
        
    #     # Verify the signature
    #     notation verify ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # - name: Output signed image reference
    #   run: |
    #     echo "Signed image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
