name: Sign Container Image with Notation Trusted Signing Plugin

on:
  workflow_dispatch:

env:
  REGISTRY: notationreg.azurecr.io
  IMAGE_NAME: hello-world
  IMAGE_TAG: ${{ github.sha }}

jobs:
  sign-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC token
      contents: read    # Required to read repository contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure CLI Login with Federated Credentials
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.REGISTRY }}

    - name: Install Notation
      uses: notaryproject/notation-action/setup@v1
      with:
        version: "1.3.2"

    - name: Build and Push Docker Image
      run: |
        # Build the image
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        
        # Push the image
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Sign Image with Notation
      uses: notaryproject/notation-action/sign@v1
      with:
        target_artifact_reference: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        signature_format: cose
        plugin_name: azure-kv  # Use Azure Key Vault plugin
        plugin_url: https://github.com/Azure/notation-azure-kv/releases/download/v1.0.1/notation-azure-kv_1.0.1_linux_amd64.tar.gz
        plugin_checksum: sha256:7a2b4ecfa095e42a3e9e7e77c0e5c9f51c0d6c3e8a9b1f3e2d4c5a6b7c8d9e0f1
        key_id: ${{ secrets.AZURE_KEY_VAULT_KEY_ID }}
        plugin_config: |
          self_signed=false
        
    - name: Verify Signature
      run: |
        # Install notation if not already available in PATH
        notation version
        
        # Verify the signature
        notation verify ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Output signed image reference
      run: |
        echo "Signed image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
